

app:
  name: core-api
  host: 0.0.0.0
  port: 8888


mysql:
  dataSource: root:123456@tcp(172.20.0.1:3306)/demo?charset=utf8&parseTime=True&loc=Local

redis:
  addr: 172.20.0.1:6379
  passwd: 
  db: 0 

